name: Build and Push Images

on:
  workflow_dispatch:
    inputs:
      component:
        description: 'Component to bump'
        required: true
jobs:
  build_push:
    name: Check user imnput
    runs-on: ubuntu-latest
    steps:
      - name: echo input
        run: |
          echo "Component tobump: ${{ github.event.inputs.component }}"
