name: Build and Push Images

on:
  schedule:
  - cron: '59 6 * * *'
  workflow_dispatch:
    branches:
    - main
    - release-*
    inputs:
      component:
        description: 'Component to bump'
        required: true
jobs:
  build_push:
    name: Check user imnput
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo input
        run: |
          echo "Component tobump: ${{ github.event.inputs.component }}"
          cat release.txt
