name: Build and Push Images

on:
  push:
    branches:
      - main
      - release-*
jobs:
  build_push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: set version
        run: echo "VERSION=v1.2.3" >> $GITHUB_ENV
      - name: set var in main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "TAG=${VERSION}-unstable" >> $GITHUB_ENV
      - name: set var in release
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo "TAG=${VERSION}" >> $GITHUB_ENV
      - nane: echo
        run: echo {{ env.TAG }}

